### ISSUE TITLE
와인 주문 페이지에서의 가격 정책

### ISSUE THREAD

**Issue by betterafter** [epiccorp-team/epicone-review#3]
- [ ] Wine 정보에 price 정보가 있는데, 이것과 무관하게 하드 코딩을 해야하는 것일까요? 또는 해당 정보를 사용해도 되나요?
- [ ] 그 외 하드코딩 없이 Wine 클래스에 있는 정보를 활용해도 되나요?

**Comment by scriabinEtude** [comment]
넵 price 정보 사용해도 됩니다.
활용할 수 있는 정보가 있다면 하드코딩 없이 가셔도 좋아요
